### ISSUE TITLE
Why We aren't using `GraphQL`? 🐌 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-graphQL#23]
As you can see from the last-updated date on this repo, 🧑‍💻 
<img width="284" alt="image" src="https://user-images.githubusercontent.com/194400/207606770-d8c06dd9-45fd-4b67-bfd7-56414eecdd2b.png">

we haven't expanded our knowledge of `GraphQL` in a few years. ⌛ 
We have experience of using `GraphQL` in production in several places. 🏦 
It's **_universally_ slower** than the equivalent `REST API` or `Socket` stream ... 🐌 

On the _surface_ it seems like a good idea to model your desired response data in the query. 💭 
You can traverse a graph of data and return the related results. 😍 
What's not to like? 🤷‍♂️ 

# `GraphQL` Makes Your App _Sloooooooooooooowww_ ... 🐌 

![fork-in-road-graphql-embedded](https://user-images.githubusercontent.com/194400/207591235-34caaa37-c02a-4599-bb32-ddf10b2ac767.jpg)

# Our Experience 

We've used `GraphQL` in 3 contexts: 
1. `Serverless` - `AWS Lambda` functions were used to resolve data from `DynamoDB`. These added a _minimum_ of **`200ms`** latency to each query sent from the frontend and in some cases the resolver would take **`800ms`**. This is an _unacceptable_ delay that made _every_ interaction on the Mobile App even on a **`1Gbps`** connection feel ***Sloooooowww*** 🐌 
2. As-a-service -  an Apollo Server was run on an EC2 instance and served all the `GraphQL` queries, which then had to be resolved to several other services e.g. 3<sup>rd</sup> Party APIs. This was a _marginal_ improvement over running `GraphQL` "serverless" but still created duplication of effort because every 3<sup>rd</sup> Party API required it's own "resolver". There was so much code in the repo and it ended up being so slow it was _embarrassing_ to watch people using the App in demos ... ⏳ 🤦‍♂️ 
  > **Note**: I wrote **one** of the resolvers and mostly copy-pasted code from another place. That was the norm. Copy-pasted code _everywhere_!! When I suggested making a library the "Director of Engineering" said "no". Horrible maintenance nightmare!!
3. Integrated - a recent client project used `Absinthe` in `Elixir` https://github.com/absinthe-graphql/absinthe it was _faster_ than the `Apollo` Server but instead of defining data in 2 places, now it's 3!! Each `GraphQL` endpoint requires it's own [`Schema`](https://hexdocs.pm/absinthe/schemas.html) which then resolves to function that retrieves data from `Ecto` ... i.e. Maintenance Nightmare! 😢 

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/194400/207597429-57e9452d-3689-4ec2-9fba-fcc1243534bc.png">

Whenever you read the word "_modern_" think "**more _complex_**" or "***worse***". 
Adding a layer of `GraphQL` on top of your existing database means you have to _resolve_ the queries.
This means you have to write _all_ code twice and ***maintain*** those queries. 
When something changes, you have to change and _test_ it in both places.
This automatically increases [in many cases _doubles_] costs. 
And what for? Does it offer a _speed boost_ to the people _using_ the App you're building? 
Heck no!! It makes your App slower. In _every_ case. 

So why do people keep doing it? 🤷‍♂️ 
One word: 

# _Fashion_ 🕴️ 

![image](https://user-images.githubusercontent.com/194400/207598601-67d34910-18ef-4ef8-bc45-f87457391c89.png)
[/fashion-fails](https://www.ranker.com/list/funny-fashion-fails/nathandavidson)

Fashion doesn't have to be _practical_. It's all about being _noticed_. 
People who are bored and generally don't have much substance to them feel the need to [peacock](https://en.wikipedia.org/wiki/Peacocking) for attention ... 
It's no different in the tech world. 
Why build a "boring" low-latency API that means people using your App can get their job done _faster_ when you can build a slow API with a "Graph" interface that is substantially slower? Answer: to impress your peers with cool-sounding names. 🙄 

Chose the "boring" but _fast_ solution _every_ time.
Leave the complexity to your competitors.
If someone on your team is _tempted_ to use `GraphQL` tell them to create a sample project with non-trivial data and compare the query resolution of the `GraphQL` API vs. using "raw" Websockets. 

There may be a use-case where `GraphQL` is "better", e.g. where you would need to perform _multiple_ `REST API` queries to retrieve the same data. 

# Dynamic Data / Response

A use-case that _could_ make sense: 
We originally explored using `GraphQL` when we were re-building Search at a travel company where there were multiple parameters such as number of passengers, ages, meal preferences, etc. There wasn't one _single_ API endpoint that could return all the data at once. So we used GraphQL to dynamically build the query in the front-end, assemble all the required bits in the back-end and then the result would have the same "shape" as the query so it would be easier to display.
That was the _theory_ at least. The _reality_ was that we were just shifting query complexity from one place to another.
The resolvers in the `GraphQL` server still had to "assemble" all the data to service the query. The `GraphQL` server made as many as 30 `HTTP` requests to return the needed data from various internal microservices. ⏳ 
And if you know anything about asynchronous request processing and the [theory of constraints](https://en.wikipedia.org/wiki/Theory_of_constraints), this meant that the response returned by the `GraphQL` server was subjected to the _slowest_ returning `HTTP` request. i.e. if one request took **`1300ms`** to return, it didn't matter if the others were **`200-400ms`** the response was always slow.

This is a _horrible_ way to build an API!! 😕 

Instead, the way that respects the person/people _using_ the App is to respond as quickly as possible with the most relevant data and then gradually return more data as it become available. 

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/194400/207605190-1e581e1b-ede4-404c-aae6-3d9187c6fd85.png">

You don't need **`Yeezys`** to go for a walk outside, you need affordable comfortable & functional shoes.
You don't need **`GraphQL`** to build an API/App. You need something _fast_ that isn't _fashionable_. 

If you're building something "küle" to impress someone, do it as a side-project in your own time. 
But _please_ run some benchmarks on it so you know how slow and pointless it is!! 🙏 
Build your API around the queries people make most often and optimise for the speed not fashion.

**Comment by nelsonic** [comment]
I hereby invite anyone using `GraphQL` in Production to share ***metrics*** of **response times** being ***faster*** using `GraphQL` instead of "boring" **`REST` API**. 🙏 

If you care about the **`people` _using_ your App** and don't want to _waste_ their time on _every_ request/response. 
You won't be using `GraphQL`; at least not as the core API. 


A couple of years ago, `Twitter` made a splash talking about their "V2 API":

https://about.sourcegraph.com/blog/graphql/graphql-at-twitter
<img width="1032" alt="graphql-at-twitter-no-performance" src="https://user-images.githubusercontent.com/194400/207619864-1417d0f1-85ad-4118-9275-3cf51c35cb02.png">

https://blog.twitter.com/engineering/en_us/topics/infrastructure/2020/rebuild_twitter_public_api_2020
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/194400/207610845-bf7eb8af-8b8a-4408-bbc2-29a40e30712b.png">

Seriously, read through this Engineering Blog post.
Search for instances of engineering-focussed keywords such as "performance" or "latency":

<img width="869" alt="twitter-api-latency" src="https://user-images.githubusercontent.com/194400/207618431-4bef28c2-5348-4c4e-b2c1-b204f314d019.png">

<img width="869" alt="twitter-latency-perf" src="https://user-images.githubusercontent.com/194400/207618482-10826dae-cd12-4e9a-9937-4bbfe47fda00.png">

### "_Latency is a time delay between the cause and the effect of some physical change in the system being observed._" ~ https://en.wikipedia.org/wiki/Latency_(engineering)

# What was _Wrong_ With the "Old" API?

The "old" API was perfectly fine. We used it: e.g: [dwyl/meteor-search](https://github.com/dwyl/meteor-search/blob/master/server/seed_content.js#L6)
There was a real-time socket based API and everything was perfectly stable.
But there was a [shiny new toy](https://en.wikipedia.org/wiki/Shiny_object_syndrome) and Twitter Devs couldn't help themselves. They re-built backend as microservices and API using `GraphQL` ... 
_Billions_ burned on a bonfire. No improvement to the API. No leap in usage. 💸 🔥 


# _Meanwhile_ ... 

Meanwhile, _days_ after Elon acquired the [**_LOSS_ Making**](https://github.com/dwyl/learn-react/issues/23#issuecomment-1308947186) platform, 
they _magically_ reduced core service Latency by **`400ms`**:
https://twitter.com/elonmusk/status/1597829226572705793
<img width="892" alt="image" src="https://user-images.githubusercontent.com/194400/207611509-1c84d408-38ee-4f08-8e1a-b9db6d043a0e.png">

https://developer.twitter.com/en/search-results?q=graphql
<img width="1190" alt="twitter-graphql-no-results" src="https://user-images.githubusercontent.com/194400/207608985-6a8c5426-d9f9-4c93-9709-444aa603f208.png">

# Coincidence? 

The whole team of people that worked on `GraphQL` at Twitter left: https://twitter.com/hashtag/LoveWhereYouWorked
see: [linkedin.com/feed/update/urn:li:activity:7004090039634644993](https://www.linkedin.com/feed/update/urn:li:activity:7004090039634644993?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A7004090039634644993%29)

Very curious _why_ ... 💭 
Obviously the _superficial_ reason is that Elon is a douche and nobody wants to work for/with him. 🤦‍♂️ 
But what is the **_real_ reason**? 🤷‍♂️ 
Could it be that Twitter just doesn't _need_ `GraphQL` to provide it's services and APIs? 🤔 

Sadly, you won't read about the complexity on any of the promotional materials on https://www.graphql.com ...

Recommend reading:
+ https://blog.logrocket.com/graphql-vs-rest-api-why-you-shouldnt-use-graphql
+ https://dev.to/andyrewlee/why-i-no-longer-use-graphql-for-new-projects-1oig

Why I Don’t Use GraphQL Anymore: https://youtu.be/S1wQ0WvJK64?t=187
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/194400/207627910-bca180e9-7811-4861-8183-40b890f5f31d.png">

# "deep well of complexity" ... 

if your objective is job security, then _definitely_ implement `GraphQL` _everywhere_! 
But if you want to keep something _simple_ and _performant_, give it a _hard_ pass.

**Comment by iteles** [comment]
This issue feels like it needs to be in the readme!

**Comment by nelsonic** [comment]
@iteles we _could_ put it in the `README.md` but I just wanted to capture some thoughts so that I could share. 🔗 
Ultimately, I'm not going to change the minds of the Devs who have been brainwashed by Facebook's Marketing Machine. 😕

**Comment by nelsonic** [comment]
Sadly, **`Facebook`** is not in the _business_ of _minimising_ response times in their services.
In fact, quite the opposite is true they _measure_ and _optimise_ for **time-on-site**:

## Facebook's objective is to: <br />"_consume as much of your time_ <br />_and conscious attention as possible_." <br />~ [Sean Parker](https://github.com/dwyl/learn-react/issues/23#issuecomment-647521076), Former Facebook President 

Therefore they don't _care_ if each/every request takes **`100-400ms longer`**.
They _want_ the service to be _just_ "fast enough" so people don't quit the App,
but those extra **`ms`** per page load add up to more time spent on the site.
They have a **_perverse_ incentive** to ***not*** make their service as **_fast_ as possible**!!
And what's more, because they are systematically slowing down their _own_ service,
they have a **_huge_ vested interest** in proliferating the technology.

The more companies use `GraphQL` to make their APIs/Apps/Services ***substantially slower***,
the more **`Facebook`** & Co. with their **_deliberately_ slow** API will appear to be "normal". 
It's not "normal" to _waste_ people's time, but that's `Facebook`'s _entire_ business model.

**Comment by nelsonic** [comment]
https://bessey.dev/blog/2024/05/24/why-im-over-graphql/
I Am Done With Graph QL After 6 Years: https://youtu.be/XBUsRVepF-8
<img width="861" alt="image" src="https://github.com/user-attachments/assets/ef71dcb4-118c-4b73-a4dc-c6be806192a3">

https://www.softwareatscale.dev/p/the-hidden-performance-cost-of-nodejs
The Hidden Cost Of GraphQL And NodeJS: https://youtu.be/i0YfiQlzv6M
<img width="858" alt="image" src="https://github.com/user-attachments/assets/74d81594-b34e-40f1-8921-124fe182d61c">
